server:
  port: 8083
spring:
  application:
    name: delivery-api
  jackson:
    serialization:
      fail-on-empty-beans: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-44-195-162-77.compute-1.amazonaws.com:5432/d8mtsmp6bjq9ej?sslmode=disable
    username: azypurgjgawepl
    password: 759ce1829249e3f81b9464268c118d818d1e84e1ef7889be90f7dd9636a802f3
  jpa:
    generate-ddl: 'false'
    database: POSTGRESQL
    properties:
      hibernate:
        format_sql: true
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 100
          lob:
            non_contextual_creation: 'true'
      org:
        hibernate:
          flushMode: COMMIT
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
  sql:
    init:
      continue-on-error: 'false'
      platform: postgresql


